/**
 * Constantes des scopes pour les variables Figma
 */
export const SCOPES = {
  FLOAT: {
    ALL: "ALL_SCOPES",
    TEXT_CONTENT: "TEXT_CONTENT",
    CORNER_RADIUS: "CORNER_RADIUS",
    WIDTH_HEIGHT: "WIDTH_HEIGHT",
    GAP: "GAP",
    OPACITY: "OPACITY",
    STROKE_FLOAT: "STROKE_FLOAT",
    EFFECT_FLOAT: "EFFECT_FLOAT",
    FONT_VARIATIONS: "FONT_VARIATIONS",
    FONT_WEIGHT: "FONT_WEIGHT",
    FONT_SIZE: "FONT_SIZE",
    LINE_HEIGHT: "LINE_HEIGHT",
    LETTER_SPACING: "LETTER_SPACING",
    PARAGRAPH_SPACING: "PARAGRAPH_SPACING",
    PARAGRAPH_INDENT: "PARAGRAPH_INDENT",
  },
  COLOR: {
    ALL: "ALL_SCOPES",
    ALL_FILLS: "ALL_FILLS",
    FRAME_FILL: "FRAME_FILL",
    SHAPE_FILL: "SHAPE_FILL",
    TEXT_FILL: "TEXT_FILL",
    STROKE_COLOR: "STROKE_COLOR",
    EFFECT_COLOR: "EFFECT_COLOR",
  },
  STRING: {
    ALL: "ALL_SCOPES",
    TEXT_CONTENT: "TEXT_CONTENT",
    FONT_FAMILY: "FONT_FAMILY",
    FONT_STYLE: "FONT_STYLE",
  },
} as const;
